// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV6M0YJDGzkP1DZJVIaqf-fV1BskQNWbE',
    appId: '1:865190600063:web:3609bb32ddfcbefbfc8e4a',
    messagingSenderId: '865190600063',
    projectId: 'daily-routine-b4799',
    authDomain: 'daily-routine-b4799.firebaseapp.com',
    storageBucket: 'daily-routine-b4799.firebasestorage.app',
    measurementId: 'G-S47DGBVD5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVA3LB6_eXtrvOx4XekX2w_fW2bdas7r4',
    appId: '1:865190600063:android:56641e7425a92dfcfc8e4a',
    messagingSenderId: '865190600063',
    projectId: 'daily-routine-b4799',
    storageBucket: 'daily-routine-b4799.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU_nSH2OQ9GJ33fT4tQ9uHjdlyDjI3aKw',
    appId: '1:865190600063:ios:8c1693a6bf5cbc84fc8e4a',
    messagingSenderId: '865190600063',
    projectId: 'daily-routine-b4799',
    storageBucket: 'daily-routine-b4799.firebasestorage.app',
    iosBundleId: 'com.example.mdr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU_nSH2OQ9GJ33fT4tQ9uHjdlyDjI3aKw',
    appId: '1:865190600063:ios:8c1693a6bf5cbc84fc8e4a',
    messagingSenderId: '865190600063',
    projectId: 'daily-routine-b4799',
    storageBucket: 'daily-routine-b4799.firebasestorage.app',
    iosBundleId: 'com.example.mdr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV6M0YJDGzkP1DZJVIaqf-fV1BskQNWbE',
    appId: '1:865190600063:web:5bbe31f9940074befc8e4a',
    messagingSenderId: '865190600063',
    projectId: 'daily-routine-b4799',
    authDomain: 'daily-routine-b4799.firebaseapp.com',
    storageBucket: 'daily-routine-b4799.firebasestorage.app',
    measurementId: 'G-825HKFL6CD',
  );
}
